#Alternatively, this yaml can be added to the headless-services.yaml
#using 3 dashes (---)
apiVersion: v1
kind: Service
metadata:
  name: dxemssql-3
spec:
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: dxemssql-3
  ports:
  - name: dxl
    protocol: TCP
    port: 7979
  - name: dxc-tcp
    protocol: TCP
    port: 7980
  - name: dxc-udp
    protocol: UDP
    port: 7981
  - name: sql
    protocol: TCP
    port: 1433
  - name: listener
    protocol: TCP
    port: 14033